version: '3'

services:
  model_a:
    build:
      context: .
      dockerfile: Dockerfile.model_a
    container_name: model_a
    volumes:
      - ./logs:/logs
    ports:
      - "5001:5000"

  model_b:
    build:
      context: .
      dockerfile: Dockerfile.model_b
    container_name: model_b
    volumes:
      - ./logs:/logs
    ports:
      - "5002:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf